version: '3.8'

services:
  backend:
    build: .
    container_name: flask_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/main_prueba/instance
    environment:
      SQLALCHEMY_DATABASE_URI: "sqlite:///greenergy_insights.db"
      REE_API_TOKEN: "ddcbd54fa41b494243f3a6094062af3f41a4675956a8f50a2b92b80bd0fbc71a"